language: java
jdk:
  - oraclejdk8
install: 
  - mvn clean install -Dmaven.test.skip=true
after_success:
  - mvn clean deploy --settings deploy.settings.xml -DdeployAtEnd=true -f tycho-pom.xml
notifications:
  email:
    on_success: change
    on_failure: change

cache:
  directories:
  - $HOME/.m2
