dist: trusty
language: java
jdk:
- oraclejdk8
install:
- mvn clean install -Dmaven.test.skip=true
- mvn clean deploy --settings deploy.settings.xml -DdeployAtEnd=true -f tycho-pom.xml
notifications:
  email:
    on_success: change
    on_failure: change
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: tx2xt95gFgS69hjT828Bo10DlwFFDLz9LcTWbpXdXajmb7Fkka04rzGfwQ2MH6waBBatIhqAViGW8vAxZQJrFZ0V2MlbXnIV2wZ3ibAPZlP8zI1+ZgHIHhGKEQMl1zgZjyPAr7968bkHtxAVPHvqfAAhXsyWZ1GJT+3Xfy82IJc=
  - secure: fvGrSE5oTYnQTajhhExEx+6K3p/NdCDHPDgtHbnFK65QO586FPpZ6Mo+PJpilvk0obcoJw+R79nOYT2gGrW3Ki4Meguvagi5HnOW27q/N0U7+a3kgVE2upCvZYTFL8phrx9BNfMSe4NS+FxahHIINEQDI7y1ZFJ5lQ0ovX34iQc=
